export const formSupplier = [
    {
        key: "name",
        value: "name",
        label: "Supplier name",
        required: true,
        message: "Enter supplier name.",
        placeholder: "Enter supplier name",
        type: "default",
        default_value: "",
        displayLenght: 200,
    },
    {
        key: "product",
        value: "product",
        label: "Product",
        required: false,
        message: "",
        placeholder: "Enter product",
        type: "default",
        default_value: "",
        displayLenght: 150,
    },
    {
        key: "email",
        value: "email",
        label: "Email",
        required: true,
        message: "Enter email.",
        placeholder: "Enter email",
        type: "email",
        default_value: "",
        displayLenght: 300,
    },

    {
        key: "category",
        value: "category",
        label: "Category",
        required: false,
        message: "",
        placeholder: "Select product category",
        type: "select",
        default_value: [],
        displayLenght: 150,
    },
    {
        key: "price",
        value: "price",
        label: "Buying Price",
        required: false,
        message: "",
        placeholder: "Enter buying price",
        type: "number",
        default_value: "",
        displayLenght: 100,
    },
    {
        key: "contact",
        value: "contact",
        label: "Contact Number",
        required: false,
        message: "",
        placeholder: "Enter contact number",
        type: "tel",
        default_value: "",
        displayLenght: 150,
    },
    {
        key: "type",
        value: "isTasking",
        label: "Type",
        required: false,
        message: "",
        placeholder: "",
        type: "checkbox",
        default_value: null,
        displayLenght: 150,
    },
    {
        key: "active",
        value: "active",
        label: "Active",
        required: false,
        message: "",
        placeholder: "Enter active",
        type: "number",
        default_value: "",
        displayLenght: 80,
    },
];
